#pragma once

// Multi-file logger backed by spdlog (Debug only; Release → no-ops).
//
// Log::Init()        — creates main.log at trace level (before Config).
// Log::InitModules()  — creates per-module loggers + applies Config level
//                       to all loggers. Call after Config::Load().
//
// General macros  →  <steam>/manifestdexcore/main.log
// Module macros   →  <steam>/manifestdexcore/<module>.log
//
// Adding a new module logger:
//   1. Add  MDX_MOD(NewMod, "newmod")  in mdx_log_modules.h.
//   2. Run CMake configure (the LOG_NEWMOD_* macros are auto-generated).

#ifdef MANIFESTDEXCORE_LOGGING_ENABLED

#ifndef SPDLOG_ACTIVE_LEVEL
    #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#endif

#include <spdlog/spdlog.h>
#include <spdlog/fmt/bin_to_hex.h>
#include <spdlog/sinks/basic_file_sink.h>
#include "OSTPlatform/include/DynamicLibrary.h"
#include <memory>

namespace Log {
    void Init(OSTPlatform::DynamicLibrary::ModuleHandle selfModule);
    void InitModules();
    void ApplyConfigLevel();

    // Route OSTPlatform's logging facade into the host's "platform" logger.
    // Call once after InitModules() (the Platform logger must exist first).
    void InstallPlatformLogSink();

    inline std::shared_ptr<spdlog::logger> Main;

    // Module loggers — auto-generated from mdx_log_modules.h
    #define MDX_MOD(v, f) inline std::shared_ptr<spdlog::logger> v;
    #include "mdx_log_modules.h"
    #undef MDX_MOD
}

// ── General-purpose (main.log) ──────────────────────────────────────
#define LOG_TRACE(...) SPDLOG_LOGGER_TRACE(Log::Main, __VA_ARGS__)
#define LOG_DEBUG(...) SPDLOG_LOGGER_DEBUG(Log::Main, __VA_ARGS__)
#define LOG_INFO(...)  SPDLOG_LOGGER_INFO(Log::Main, __VA_ARGS__)
#define LOG_WARN(...)  SPDLOG_LOGGER_WARN(Log::Main, __VA_ARGS__)
#define LOG_ERROR(...) SPDLOG_LOGGER_ERROR(Log::Main, __VA_ARGS__)

#else  // MANIFESTDEXCORE_LOGGING_ENABLED

#include "OSTPlatform/include/DynamicLibrary.h"

namespace Log {
    inline void Init(OSTPlatform::DynamicLibrary::ModuleHandle) {}
    inline void InitModules() {}
    inline void ApplyConfigLevel() {}
    inline void InstallPlatformLogSink() {}
}

#define LOG_TRACE(...)  ((void)0)
#define LOG_DEBUG(...)  ((void)0)
#define LOG_INFO(...)   ((void)0)
#define LOG_WARN(...)   ((void)0)
#define LOG_ERROR(...)  ((void)0)

#endif  // MANIFESTDEXCORE_LOGGING_ENABLED

// ── Per-module macros (auto-generated by cmake/LogMacros.cmake) ────
// Generated header has its own #ifdef MANIFESTDEXCORE_LOGGING_ENABLED guard.
#include "mdx_log_macros.h"
